---
- name: Đổi mật khẩu Administrator
  ansible.windows.win_user:
    name: "{{ ansible_user }}"
    password: "{{ password_new }}"
    state: present

- name: Cập nhật mật khẩu mới vào runtime memory
  ansible.builtin.set_fact:
    ansible_password: "{{ password_new }}"